import Head from 'next/head'
import { Inter } from '@next/font/google'

import Header from '../components/header-section/header'
import Hero from '../components/hero-section/hero'
import Projects from '../components/projects-section/projects'
import About from '../components/about-section/about'
import Skills from '../components/skills-section/skills'
import Footer from '../components/footer-section/footer'

export default function Home() {
  return (
    <>
      <div className='mx-auto'>
        <Head>
          <title>Miguel Ferreira</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <section className="main-container h-screen overflow-auto">
            <Header />
            <Hero />
            <Projects />
            <Skills />
            <About />
            <Footer />
          </section>
        </main>
      </div>
    </>
  )
}
